# Set app name of consumer Deployment.
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: consumer
  labels:
    app.kubernetes.io/name: ping-pong
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ping-pong
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping-pong
    spec:
      containers:
        - name: consumer
          env:
            # Demonstration of passing an argument by flag:
            - name: CONSUMER_APP_ARGS
              value: "--ping-pong.players=101"
            # Demonstration of passing an argument by environment:
            - name: PING_PONG_PERIOD
              value: "2s"
---
# Set the application name within the consumer Service.
apiVersion: v1
kind:       Service
metadata:
  name: consumer
  labels:
    app.kubernetes.io/name: ping-pong
spec:
  selector:
    app.kubernetes.io/name: ping-pong
